version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/intekplus
    overwrite: yes
permissions:
  - object: /home/ubuntu/intekplus
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: /home/ubuntu/intekplus/deploy.sh
      timeout: 300
      runas: ubuntu
